// Generated by scripts/import-lzc-gallery.mjs from the curated, deduplicated LZ Custom archive.
export const lzGalleryProjects = [
  {
    "id": "lz-042",
    "src": "/inspiration/lz-archive/lz-042.webp",
    "title": "Kitchens inspiration 01",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 1"
  },
  {
    "id": "lz-046",
    "src": "/inspiration/lz-archive/lz-046.webp",
    "title": "Bathrooms inspiration 01",
    "detail": "Bathroom layouts, vanities, tile, and stone finishes",
    "category": "Bathrooms",
    "alt": "AI-generated LZ Custom bathrooms inspiration concept 1"
  },
  {
    "id": "lz-097",
    "src": "/inspiration/lz-archive/lz-097.webp",
    "title": "Commercial inspiration 01",
    "detail": "Commercial interiors and durable workplace finishes",
    "category": "Commercial",
    "alt": "AI-generated LZ Custom commercial inspiration concept 1"
  },
  {
    "id": "lz-124",
    "src": "/inspiration/lz-archive/lz-124.webp",
    "title": "Installation inspiration 01",
    "detail": "Measurement, delivery, fitting, and installation concepts",
    "category": "Installation",
    "alt": "AI-generated LZ Custom installation inspiration concept 1"
  },
  {
    "id": "lz-019",
    "src": "/inspiration/lz-archive/lz-019.webp",
    "title": "Tile & patterns inspiration 01",
    "detail": "Tile layouts, patterns, spacing, and surface ideas",
    "category": "Tile & patterns",
    "alt": "AI-generated LZ Custom tile & patterns inspiration concept 1"
  },
  {
    "id": "lz-030",
    "src": "/inspiration/lz-archive/lz-030.webp",
    "title": "Fabrication inspiration 01",
    "detail": "Stone fabrication, shop work, and precision processes",
    "category": "Fabrication",
    "alt": "AI-generated LZ Custom fabrication inspiration concept 1"
  },
  {
    "id": "lz-001",
    "src": "/inspiration/lz-archive/lz-001.webp",
    "title": "Kitchens inspiration 02",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 2"
  },
  {
    "id": "lz-110",
    "src": "/inspiration/lz-archive/lz-110.webp",
    "title": "Bathrooms inspiration 02",
    "detail": "Bathroom layouts, vanities, tile, and stone finishes",
    "category": "Bathrooms",
    "alt": "AI-generated LZ Custom bathrooms inspiration concept 2"
  },
  {
    "id": "lz-099",
    "src": "/inspiration/lz-archive/lz-099.webp",
    "title": "Commercial inspiration 02",
    "detail": "Commercial interiors and durable workplace finishes",
    "category": "Commercial",
    "alt": "AI-generated LZ Custom commercial inspiration concept 2"
  },
  {
    "id": "lz-022",
    "src": "/inspiration/lz-archive/lz-022.webp",
    "title": "Fabrication inspiration 02",
    "detail": "Stone fabrication, shop work, and precision processes",
    "category": "Fabrication",
    "alt": "AI-generated LZ Custom fabrication inspiration concept 2"
  },
  {
    "id": "lz-070",
    "src": "/inspiration/lz-archive/lz-070.webp",
    "title": "Kitchens inspiration 03",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 3"
  },
  {
    "id": "lz-126",
    "src": "/inspiration/lz-archive/lz-126.webp",
    "title": "Painting inspiration 01",
    "detail": "Interior coating and commercial painting ideas",
    "category": "Painting",
    "alt": "AI-generated LZ Custom painting inspiration concept 1"
  },
  {
    "id": "lz-002",
    "src": "/inspiration/lz-archive/lz-002.webp",
    "title": "Kitchens inspiration 04",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 4"
  },
  {
    "id": "lz-038",
    "src": "/inspiration/lz-archive/lz-038.webp",
    "title": "Kitchens inspiration 05",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 5"
  },
  {
    "id": "lz-043",
    "src": "/inspiration/lz-archive/lz-043.webp",
    "title": "Kitchens inspiration 06",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 6"
  },
  {
    "id": "lz-085",
    "src": "/inspiration/lz-archive/lz-085.webp",
    "title": "Kitchens inspiration 07",
    "detail": "Kitchen layouts, cabinetry, and finish combinations",
    "category": "Kitchens",
    "alt": "AI-generated LZ Custom kitchens inspiration concept 7"
  },
  {
    "id": "lz-047",
    "src": "/inspiration/lz-archive/lz-047.webp",
    "title": "Bathrooms inspiration 03",
    "detail": "Bathroom layouts, vanities, tile, and stone finishes",
    "category": "Bathrooms",
    "alt": "AI-generated LZ Custom bathrooms inspiration concept 3"
  },
  {
    "id": "lz-048",
    "src": "/inspiration/lz-archive/lz-048.webp",
    "title": "Bathrooms inspiration 04",
    "detail": "Bathroom layouts, vanities, tile, and stone finishes",
    "category": "Bathrooms",
    "alt": "AI-generated LZ Custom bathrooms inspiration concept 4"
  },
  {
    "id": "lz-098",
    "src": "/inspiration/lz-archive/lz-098.webp",
    "title": "Commercial inspiration 03",
    "detail": "Commercial interiors and durable workplace finishes",
    "category": "Commercial",
    "alt": "AI-generated LZ Custom commercial inspiration concept 3"
  },
  {
    "id": "lz-100",
    "src": "/inspiration/lz-archive/lz-100.webp",
    "title": "Commercial inspiration 04",
    "detail": "Commercial interiors and durable workplace finishes",
    "category": "Commercial",
    "alt": "AI-generated LZ Custom commercial inspiration concept 4"
  },
  {
    "id": "lz-125",
    "src": "/inspiration/lz-archive/lz-125.webp",
    "title": "Installation inspiration 02",
    "detail": "Measurement, delivery, fitting, and installation concepts",
    "category": "Installation",
    "alt": "AI-generated LZ Custom installation inspiration concept 2"
  },
  {
    "id": "lz-149",
    "src": "/inspiration/lz-archive/lz-149.webp",
    "title": "Installation inspiration 03",
    "detail": "Measurement, delivery, fitting, and installation concepts",
    "category": "Installation",
    "alt": "AI-generated LZ Custom installation inspiration concept 3"
  },
  {
    "id": "lz-151",
    "src": "/inspiration/lz-archive/lz-151.webp",
    "title": "Installation inspiration 04",
    "detail": "Measurement, delivery, fitting, and installation concepts",
    "category": "Installation",
    "alt": "AI-generated LZ Custom installation inspiration concept 4"
  },
  {
    "id": "lz-018",
    "src": "/inspiration/lz-archive/lz-018.webp",
    "title": "Tile & patterns inspiration 02",
    "detail": "Tile layouts, patterns, spacing, and surface ideas",
    "category": "Tile & patterns",
    "alt": "AI-generated LZ Custom tile & patterns inspiration concept 2"
  },
  {
    "id": "lz-020",
    "src": "/inspiration/lz-archive/lz-020.webp",
    "title": "Tile & patterns inspiration 03",
    "detail": "Tile layouts, patterns, spacing, and surface ideas",
    "category": "Tile & patterns",
    "alt": "AI-generated LZ Custom tile & patterns inspiration concept 3"
  },
  {
    "id": "lz-083",
    "src": "/inspiration/lz-archive/lz-083.webp",
    "title": "Tile & patterns inspiration 04",
    "detail": "Tile layouts, patterns, spacing, and surface ideas",
    "category": "Tile & patterns",
    "alt": "AI-generated LZ Custom tile & patterns inspiration concept 4"
  },
  {
    "id": "lz-035",
    "src": "/inspiration/lz-archive/lz-035.webp",
    "title": "Fabrication inspiration 03",
    "detail": "Stone fabrication, shop work, and precision processes",
    "category": "Fabrication",
    "alt": "AI-generated LZ Custom fabrication inspiration concept 3"
  },
  {
    "id": "lz-115",
    "src": "/inspiration/lz-archive/lz-115.webp",
    "title": "Fabrication inspiration 04",
    "detail": "Stone fabrication, shop work, and precision processes",
    "category": "Fabrication",
    "alt": "AI-generated LZ Custom fabrication inspiration concept 4"
  },
  {
    "id": "lz-127",
    "src": "/inspiration/lz-archive/lz-127.webp",
    "title": "Painting inspiration 02",
    "detail": "Interior coating and commercial painting ideas",
    "category": "Painting",
    "alt": "AI-generated LZ Custom painting inspiration concept 2"
  },
  {
    "id": "lz-136",
    "src": "/inspiration/lz-archive/lz-136.webp",
    "title": "Painting inspiration 03",
    "detail": "Interior coating and commercial painting ideas",
    "category": "Painting",
    "alt": "AI-generated LZ Custom painting inspiration concept 3"
  },
  {
    "id": "lz-004",
    "src": "/inspiration/lz-archive/lz-004.webp",
    "title": "Materials & surfaces inspiration 01",
    "detail": "Stone, laminate, wood, and countertop material ideas",
    "category": "Materials & surfaces",
    "alt": "AI-generated LZ Custom materials & surfaces inspiration concept 1"
  },
  {
    "id": "lz-005",
    "src": "/inspiration/lz-archive/lz-005.webp",
    "title": "Materials & surfaces inspiration 02",
    "detail": "Stone, laminate, wood, and countertop material ideas",
    "category": "Materials & surfaces",
    "alt": "AI-generated LZ Custom materials & surfaces inspiration concept 2"
  },
  {
    "id": "lz-025",
    "src": "/inspiration/lz-archive/lz-025.webp",
    "title": "Materials & surfaces inspiration 03",
    "detail": "Stone, laminate, wood, and countertop material ideas",
    "category": "Materials & surfaces",
    "alt": "AI-generated LZ Custom materials & surfaces inspiration concept 3"
  },
  {
    "id": "lz-094",
    "src": "/inspiration/lz-archive/lz-094.webp",
    "title": "Materials & surfaces inspiration 04",
    "detail": "Stone, laminate, wood, and countertop material ideas",
    "category": "Materials & surfaces",
    "alt": "AI-generated LZ Custom materials & surfaces inspiration concept 4"
  },
  {
    "id": "lz-007",
    "src": "/inspiration/lz-archive/lz-007.webp",
    "title": "Cabinetry & wood inspiration 01",
    "detail": "Cabinet profiles, wood tones, and built-in details",
    "category": "Cabinetry & wood",
    "alt": "AI-generated LZ Custom cabinetry & wood inspiration concept 1"
  },
  {
    "id": "lz-008",
    "src": "/inspiration/lz-archive/lz-008.webp",
    "title": "Cabinetry & wood inspiration 02",
    "detail": "Cabinet profiles, wood tones, and built-in details",
    "category": "Cabinetry & wood",
    "alt": "AI-generated LZ Custom cabinetry & wood inspiration concept 2"
  }
]
