export const services = [
  {
    slug: 'power-washing',
    name: 'Power Washing',
    eyebrow: 'Exterior care',
    description: 'Power washing for siding, walkways, patios, porches, and other exterior surfaces that need a careful reset.',
    details: ['Siding and exterior walls', 'Walkways, patios, and porches', 'Surface condition review before washing'],
    seo: 'Power washing services in Northeast Ohio for siding, patios, walkways, porches, and exterior home cleanup.',
  },
  {
    slug: 'door-repairs',
    name: 'Door Repairs',
    eyebrow: 'Doors & hardware',
    description: 'Repair sticking, sagging, damaged, or drafty doors, then get the hardware, trim, and everyday operation right.',
    details: ['Entry, interior, and storm doors', 'Hinges, latches, sweeps, and weatherstripping', 'Trim and fit adjustments'],
    seo: 'Door repair services in Northeast Ohio for sticking, sagging, damaged, and drafty entry and interior doors.',
  },
  {
    slug: 'lock-replacement',
    name: 'Lock Replacement',
    eyebrow: 'Doors & security',
    description: 'Replace worn, damaged, or outdated locks and improve everyday access at doors, garages, and outbuildings.',
    details: ['Entry and interior locks', 'Deadbolts and hardware', 'Fit and operation check'],
    seo: 'Lock replacement and door hardware installation in Northeast Ohio for homes, garages, and outbuildings.',
  },
  {
    slug: 'furniture-assembly',
    name: 'Furniture Assembly',
    eyebrow: 'Move-in help',
    description: 'Assembly help for furniture, shelving, desks, beds, cabinets, and the pieces that arrive in too many boxes.',
    details: ['Flat-pack furniture', 'Shelves, desks, and cabinets', 'Stability and placement check'],
    seo: 'Furniture assembly services in Northeast Ohio for flat-pack furniture, desks, shelving, beds, and cabinets.',
  },
  {
    slug: 'clean-up-services',
    name: 'Clean-Up Services',
    eyebrow: 'Property upkeep',
    description: 'Clear out project debris, neglected areas, move-out mess, and small property cleanup lists.',
    details: ['Post-project debris', 'Move-out and garage cleanup', 'Small exterior cleanup lists'],
    seo: 'Small property clean-up services in Northeast Ohio for garages, move-outs, project debris, and neglected areas.',
  },
  {
    slug: 'store-pickup-installation',
    name: 'Store Pickup & Installation',
    eyebrow: 'Delivery support',
    description: 'Coordinate pickup and placement for furniture, equipment, appliances, and electronics, with installation when appropriate.',
    details: ['Furniture and equipment pickup', 'Appliance placement and hookup review', 'Electronics and TV installation'],
    seo: 'Furniture, equipment, appliance, and electronics store pickup and installation in Northeast Ohio.',
  },
  {
    slug: 'painting',
    name: 'Painting',
    eyebrow: 'Interior refresh',
    description: 'Practical interior and small exterior painting for rooms, trim, doors, accent walls, and touch-up work.',
    details: ['Rooms and accent walls', 'Trim, doors, and cabinets', 'Prep and touch-ups'],
    seo: 'Interior painting and touch-up services in Northeast Ohio for rooms, trim, doors, cabinets, and accent walls.',
  },
  {
    slug: 'tile',
    name: 'Tile',
    eyebrow: 'Surface finish',
    description: 'Tile repair, replacement, backsplash work, and small tile installations with the existing conditions checked first.',
    details: ['Backsplashes and small floors', 'Tile repair and replacement', 'Grout and finish review'],
    seo: 'Small tile installation and tile repair services in Northeast Ohio for backsplashes, floors, and finished surfaces.',
  },
  {
    slug: 'pressure-washing',
    name: 'Pressure Washing',
    eyebrow: 'Hard surfaces',
    description: 'Pressure washing for decks, concrete, steps, driveways, and hard surfaces where the right pressure matters.',
    details: ['Decks and steps', 'Concrete and driveways', 'Material-safe approach'],
    seo: 'Pressure washing services in Northeast Ohio for decks, concrete, steps, driveways, and hard exterior surfaces.',
  },
  {
    slug: 'deck-repairs',
    name: 'Deck Repairs',
    eyebrow: 'Outdoor structures',
    description: 'Repair loose boards, railings, stairs, fasteners, and other manageable deck maintenance issues.',
    details: ['Boards and railings', 'Stairs and loose fasteners', 'Condition and safety review'],
    seo: 'Deck repair and maintenance services in Northeast Ohio for boards, railings, stairs, and outdoor structures.',
  },
  {
    slug: 'window-replacement',
    name: 'Window Replacement',
    eyebrow: 'Openings & trim',
    description: 'Window replacement support for measurements, removal, installation coordination, trim, and finish work.',
    details: ['Replacement planning', 'Trim and finish work', 'Installation scope review'],
    seo: 'Window replacement support in Northeast Ohio with measurement, trim, finish work, and installation scope review.',
  },
  {
    slug: 'garage-shelving',
    name: 'Garage Shelving',
    eyebrow: 'Storage systems',
    description: 'Create useful garage storage with wall-mounted shelving, work surfaces, cabinets, and organized zones.',
    details: ['Wall-mounted shelving', 'Work surfaces and cabinets', 'Layout around vehicles and equipment'],
    seo: 'Garage shelving and storage installation in Northeast Ohio for shelves, cabinets, work surfaces, and equipment zones.',
  },
  {
    slug: 'carpentry',
    name: 'Carpentry',
    eyebrow: 'Built details',
    description: 'Finish and repair carpentry for doors, trim, cabinets, shelves, built-ins, and small structural details.',
    details: ['Doors, trim, and cabinets', 'Shelves and built-ins', 'Repair and finish carpentry'],
    seo: 'Small carpentry services in Northeast Ohio for doors, trim, cabinets, shelves, built-ins, and finish work.',
  },
  {
    slug: 'woodworking',
    name: 'Woodworking',
    eyebrow: 'Custom pieces',
    description: 'Custom woodworking for practical pieces, repairs, shelves, entry details, and one-off home improvements.',
    details: ['Custom shelves and details', 'Repair and modification', 'Material and finish planning'],
    seo: 'Custom woodworking services in Northeast Ohio for shelves, entry details, repairs, modifications, and home improvements.',
  },
  {
    slug: 'epoxy',
    name: 'Epoxy',
    eyebrow: 'Resurfacing',
    description: 'Epoxy planning and surface preparation for suitable counters, floors, worktops, and decorative finishes.',
    details: ['Surface suitability review', 'Prep and repair', 'Finish and color planning'],
    seo: 'Epoxy surface preparation and finish services in Northeast Ohio for suitable floors, counters, worktops, and decorative surfaces.',
  },
  {
    slug: 'laser-cleaning',
    name: 'Laser Cleaning',
    eyebrow: 'Surface restoration',
    description: 'Precision laser cleaning for rust, paint, oxidation, soot, and surface preparation—evaluated project by project.',
    details: ['Rust and corrosion removal', 'Paint and coating removal', 'Material suitability review'],
    seo: 'Laser cleaning and surface restoration in Northeast Ohio for rust, paint, oxidation, soot, and preparation work.',
  },
]

export function servicePath(service) {
  return `/services/${service.slug}/`
}
